### PR TITLE
Implement get_spike_depth using center of mass

### PR DESCRIPTION
**Pull request by alejoe91**
Use the channel positions to compute an estimate of the spike position using the center of mass.

Changhed drift metrics computation accordingly.

- [x] update tests

Here is a notebook showing the performance with MEArec recordings with slow and fast drifts: https://gist.github.com/alejoe91/3f1672beb752eaed8997e2c4961990af

@jsiegle @colehurwitz

### CODE REVIEW

**Comment by alejoe91** [comment]
@jsiegle this is ready for review

**Comment by alejoe91** [comment]
I'll merge this as the output is exactly the same as before when locations are not passed as arguments

**Comment by jsiegle** [comment]
Ok, this looks good! Do you have any figures showing the behavior in cases where the electrodes are not linear?

**Comment by alejoe91** [comment]
You can check the gist here: https://gist.github.com/alejoe91/3f1672beb752eaed8997e2c4961990af

This is a Neuronexus 32 channels simulation with known gt somatic positions

**Comment by jsiegle** [comment]
Awesome! Apologies for missing this earlier.

**Pull request merged**
